baseurl = "https://cloudnative.barcelona/"
title = "Cloud Native Barcelona"
theme = "vncnt-hugo"
disableRSS = true
enableRobotsTXT = true
editor = "vim"
languageCode = "en"
language = "en"

# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true

[blackfriday]
  extensions = ["hardLineBreak"]

[permalinks]
  fixed = ":title/"

[params]
  author = "Cloud Native Barcelona"
  email = "hello@cloudnative.barcelona"
  description = "Cloud Native Barcelona"
  bio = """
  Cloud Native Computing Foundation (CNCF) user group dedicated to building a strong, open, diverse developer community around the Cloud Native platform and technologies in Barcelona.
  """
  avatar = "img/logo.svg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/CloudNativeBarcelona"
    twitter = "https://twitter.com/BarcelonaCloud"
    meetup = "https://www.meetup.com/Cloud-Native-Barcelona/"
    telegram = "https://t.me/CloudNativeBarcelona"
    linkedin = "https://www.linkedin.com/groups/12122493/"
    slack = "https://slack.cncf.io/"